### ISSUE TITLE
Move Bounding Box classes somewhere else for easier re-usability.

### ISSUE THREAD

**Issue by tpietzsch** [TrNdy/mastodon-tracking#8]
Candidates are `TrackMate3`, `bigdataviewer-core`, or `bigdataviewer-vistools`

**Comment by tinevez** [comment]
I would say `bigdataviewer-vistools` because it is interactive. 
Also `bigdataviewer-vistools` is a dependency of all projects that do interactive stuff with bdv.

**Comment by tinevez** [comment]
Done by Tobias quite some time ago.
